name: tests
on: [pull_request, push]
jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r requirements-dev.txt
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: pip install -r requirements.txt
      - run: pytest
